// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tzinfo.proto

module pb.tzinfo;

import google.protobuf;

enum protocVersion = 4025002;

struct Point
{
    @Proto(1) float lng = protoDefaultValue!float;
    @Proto(2) float lat = protoDefaultValue!float;
}

struct Polygon
{
    @Proto(1) Point[] points = protoDefaultValue!(Point[]);
    @Proto(2) Polygon[] holes = protoDefaultValue!(Polygon[]);
}

struct Timezone
{
    @Proto(1) Polygon[] polygons = protoDefaultValue!(Polygon[]);
    @Proto(2) string name = protoDefaultValue!string;
}

struct Timezones
{
    @Proto(1) Timezone[] timezones = protoDefaultValue!(Timezone[]);
    @Proto(2) bool reduced = protoDefaultValue!bool;
    @Proto(3) string version_ = protoDefaultValue!string;
}

struct CompressedPolygon
{
    @Proto(1) bytes points = protoDefaultValue!bytes;
    @Proto(2) CompressedPolygon[] holes = protoDefaultValue!(CompressedPolygon[]);
}

struct CompressedTimezone
{
    @Proto(1) CompressedPolygon[] data = protoDefaultValue!(CompressedPolygon[]);
    @Proto(2) string name = protoDefaultValue!string;
}

struct CompressedTimezones
{
    @Proto(1) CompressMethod method = protoDefaultValue!CompressMethod;
    @Proto(2) CompressedTimezone[] timezones = protoDefaultValue!(CompressedTimezone[]);
    @Proto(3) string version_ = protoDefaultValue!string;
}

struct PreindexTimezone
{
    @Proto(1) string name = protoDefaultValue!string;
    @Proto(2) int x = protoDefaultValue!int;
    @Proto(3) int y = protoDefaultValue!int;
    @Proto(4) int z = protoDefaultValue!int;
}

struct PreindexTimezones
{
    @Proto(1) int idxZoom = protoDefaultValue!int;
    @Proto(2) int aggZoom = protoDefaultValue!int;
    @Proto(3) PreindexTimezone[] keys = protoDefaultValue!(PreindexTimezone[]);
    @Proto(4) string version_ = protoDefaultValue!string;
}

enum CompressMethod
{
    Unknown = 0,
    Polyline = 1,
}
